import Head from "next/head";
import { Heading,Stack, Text, Box, Flex,IconButton, Icon, Input, FormControl, Button, VStack, HStack, Divider, Link, LinkOverlay, Checkbox } from "@chakra-ui/react";

//Component
import theme from "@/styles/theme";
import { useState } from "react";
import { Textarea } from "@chakra-ui/react";
import { CalendarIcon, DeleteIcon } from "@chakra-ui/icons";
import ListeTask from "@/component/ListTaxk";


interface Task {
  title: String;
  description: String;
  completed: Boolean;
}

export default function Home() {

  const [listTask, setlistTask] = useState<Task[]>([])
  const [newTask, setnewTask] = useState({
    title: '',
    description: '',
    completed: false
  })

  const handleChange = (event: any) =>{
    setnewTask({
      ...newTask,
      [event.target.name] : event.target.value
    })
  }
  
  const addTask = () =>{
   setlistTask([...listTask, newTask]) 
   setnewTask({
    title: '',
    description: '',
    completed: false
   })
  }

  const doneTask = (id: number) =>{
    const task = listTask[id]
    if (task.completed == true) {
      task.completed = false
    } else {
      if ( task.completed == false ) {
        task.completed = true
      }
    }
  }

  const deleteTask = (id: number) =>{
     const newListTask = listTask.filter((item : Task, index) => index != id)
     setlistTask(newListTask)
   }  

  return (
    <>
      <Head>
        <title>to do</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Stack p={2} pr={5} justify={'center'}  width={'100%'} alignItems={'center'}  direction={{ base: 'column', md: "column", lg: 'column'}} spacing={0}>
          <Flex width={'100%'} direction={{  base: 'column', sm:"row", md:'row', lg:'row'}}>
             <Flex direction={'row'} display={{ base:'none', sm: 'block', md:'block', lg:'block'}} w={'20%'}>
              <Heading m={5} as='h1' size='sm' >
                To do List
              </Heading>
              <Flex mt={5} direction={'column'} p={5}>
                <HStack m={1} spacing={4}>
                 <CalendarIcon/>
                 <Text variant=''>My Day</Text>
                </HStack>
              </Flex>
            </Flex> 
            <Divider orientation='vertical' />
            <Flex  justify={'center'} h={'20%'} direction={"column"} m={2}  width={{ base: "100%", sm:'50%',md:"50%",lg:"50%"}} align={'center'} >
              <Flex width={'100%'} p={4} align={'center'} justify={'space-between'}  m={{ base: '0', md: '5', lg: "5"}} >
                <Text  fontWeight={700} color={"gray.400"} fontFamily={theme.fonts.body} >
                    New Task
                </Text>
              </Flex>
              <FormControl  width={'100%'} >
                <Input value={newTask.title} onChange={handleChange} type="text" w={'100%'} name="title"  placeholder="Title"  fontSize={{ base: '14px', sm:"15px", md:'15px', lg:"15px"}} />
              </FormControl>
              <FormControl mt={5} mb={5} width={'100%'} >
                <Textarea value={newTask.description} onChange={handleChange} name="description" size={"sm"} placeholder='description' />
              </FormControl>
              { newTask.title && <Button onClick={addTask} bgColor={'black'} color={'white'}>Ajouter</Button>}
            </Flex>
            <Flex direction={'column'} width={{ base: "100%", sm:'30%',md:"30%",lg:"30%"}} >
              <Flex width={'100%'} p={4} align={'center'} justify={'space-between'}  m={{ base: '0', md: '5', lg: "5"}} >
                <Text  fontWeight={700} color={"black.400"} fontFamily={theme.fonts.body} >
                   All tasks
                </Text>
                <IconButton  aria-label='filter'/>
              </Flex>
              <Flex w={"100%"}  direction={'column'}>
                  {
                  listTask &&  listTask.map(({title, description, completed}, index) =><Box  m={0} flexDirection={'column'} h={'-moz-initial'} w={{ base: "100%", md: '100%', lg:"100%"}} bg={'gray.100'}>
                  <Flex boxShadow={"2xl"} pb={2} pt={2} pr={4} pl={4} borderRadius={15} m={2}  width={'-moz-fit-content'} align={'center'} justify={'space-between'} direction={'row'}>
                    <Checkbox  sx={{
                      h: '20px',
                      borderColor:'none',
                      px: "12px",
                          _hover: {
                            bg: 'gray',
                            h: "40px",
                            borderRadius: '30px',
                          },
                          _checked: {
                            bg: 'gray',
                            h: "40px",
                            borderRadius: '30px',
                          }
                    }} colorScheme="gray" onChange={() => doneTask(index)} />
                    <ListeTask title={title} description={description} completed={completed}  />
                    <IconButton onClick={() => deleteTask(index)} aria-label={"delete"} icon={<DeleteIcon/>} />
                  </Flex>
                  </Box> )
                }
              </Flex>
            </Flex>
          </Flex>
        </Stack>
      </main>
    </>
  );
}

