import { Box, Center } from "@chakra-ui/react";
import Head from "next/dist/shared/lib/head";
import SidebarContent from "../Sidebars";

function Layout( {children}: any ) {
    return(
        <>
        <Head>
            <title>to do</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        {/*
        sidebare 
         */}
         <SidebarContent/>
        <Box ml={{ base: 0, sm : 60}}>
            {children}
        </Box>
        {/* Footer here */}
        </>
    )
}

export default Layout;