import { Box, Center, Drawer, DrawerContent, Flex, useDisclosure} from "@chakra-ui/react";
import Head from "next/dist/shared/lib/head";
import SidebarContent from "../Sidebars";
import Header from "../Header/header";

function Layout( {children}: any ) {
    const { isOpen, onOpen, onClose } = useDisclosure();
    return(
        <>
        <Head>
            <title>to do</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <Flex  w={'100%'} direction={'row'} >
            <SidebarContent   />
            <Flex w={'100%'} direction={'column'} >
                <Header/>
                <Box  h={'100%'} w={'full'}  >
                    {children}
                </Box>
            </Flex>
        </Flex>
        {/* Footer here */}
        </>
    )
}

export default Layout;